"""Offline listings so Discover works without third-party APIs."""

from __future__ import annotations

from models import Job

DEMO_JOBS = [
    Job(
        id="demo-1",
        source="demo",
        title="Senior Software Engineer",
        company="Harborline",
        url="https://example.com/jobs/harborline-swe",
        location="Remote — United States",
        remote=True,
        salary_min=160000,
        salary_max=190000,
        salary_text="$160k–$190k",
        tags=["python", "fastapi", "postgres", "aws"],
        description="Build internal tools and APIs for a logistics network. Python, FastAPI, Postgres.",
        posted_at="2026-08-10",
    ),
    Job(
        id="demo-2",
        source="demo",
        title="Full Stack Engineer",
        company="Northstar Labs",
        url="https://example.com/jobs/northstar-fullstack",
        location="Austin, TX (hybrid)",
        remote=False,
        salary_min=145000,
        salary_max=175000,
        salary_text="$145k–$175k",
        tags=["typescript", "react", "node", "python"],
        description="Own features end to end on a TypeScript/React app with a Python service layer.",
        posted_at="2026-08-12",
    ),
    Job(
        id="demo-3",
        source="demo",
        title="Backend Engineer",
        company="Kiln",
        url="https://example.com/jobs/kiln-backend",
        location="New York, NY",
        remote=False,
        salary_min=155000,
        salary_max=185000,
        salary_text="$155k–$185k",
        tags=["python", "django", "redis", "kubernetes"],
        description="Scale a payments ledger. Strong Python, SQL, and distributed systems.",
        posted_at="2026-08-08",
    ),
    Job(
        id="demo-4",
        source="demo",
        title="Machine Learning Engineer",
        company="Fieldnote",
        url="https://example.com/jobs/fieldnote-mle",
        location="Remote — Worldwide",
        remote=True,
        salary_min=170000,
        salary_max=210000,
        salary_text="$170k–$210k",
        tags=["python", "pytorch", "llm", "aws"],
        description="Ship retrieval and ranking models into a production search stack.",
        posted_at="2026-08-11",
    ),
    Job(
        id="demo-5",
        source="demo",
        title="Product Manager, Platform",
        company="Paperclip",
        url="https://example.com/jobs/paperclip-pm",
        location="San Francisco, CA (hybrid)",
        remote=False,
        salary_min=170000,
        salary_max=200000,
        salary_text="$170k–$200k",
        tags=["product", "platform", "apis", "b2b"],
        description="Set the roadmap for developer platform APIs and usage-based billing.",
        posted_at="2026-08-09",
    ),
    Job(
        id="demo-6",
        source="demo",
        title="Data Engineer",
        company="Cedar Route",
        url="https://example.com/jobs/cedar-de",
        location="Remote — United States",
        remote=True,
        salary_min=150000,
        salary_max=180000,
        salary_text="$150k–$180k",
        tags=["python", "dbt", "snowflake", "airflow"],
        description="Model warehouse tables and keep pipelines boring and reliable.",
        posted_at="2026-08-13",
    ),
    Job(
        id="demo-7",
        source="demo",
        title="Frontend Engineer",
        company="Lumen & Co.",
        url="https://example.com/jobs/lumen-fe",
        location="Chicago, IL",
        remote=False,
        salary_min=130000,
        salary_max=155000,
        salary_text="$130k–$155k",
        tags=["javascript", "react", "css", "accessibility"],
        description="Craft a design-system-driven web app. Strong CSS and accessibility required.",
        posted_at="2026-08-07",
    ),
    Job(
        id="demo-8",
        source="demo",
        title="Site Reliability Engineer",
        company="Orbit Mail",
        url="https://example.com/jobs/orbit-sre",
        location="Remote — United States",
        remote=True,
        salary_min=165000,
        salary_max=195000,
        salary_text="$165k–$195k",
        tags=["linux", "kubernetes", "terraform", "python"],
        description="Own uptime for a high-volume email platform. On-call is real but humane.",
        posted_at="2026-08-06",
    ),
    Job(
        id="demo-9",
        source="demo",
        title="Engineering Manager",
        company="Quilt",
        url="https://example.com/jobs/quilt-em",
        location="Seattle, WA (hybrid)",
        remote=False,
        salary_min=190000,
        salary_max=230000,
        salary_text="$190k–$230k",
        tags=["management", "python", "mentoring", "delivery"],
        description="Lead a team of six backend engineers shipping a workflow product.",
        posted_at="2026-08-04",
    ),
    Job(
        id="demo-10",
        source="demo",
        title="DevOps Engineer",
        company="Redwood Health",
        url="https://example.com/jobs/redwood-devops",
        location="Denver, CO",
        remote=False,
        salary_min=140000,
        salary_max=165000,
        salary_text="$140k–$165k",
        tags=["aws", "terraform", "ci", "python"],
        description="Harden CI and cloud accounts for a HIPAA-minded health startup.",
        posted_at="2026-08-14",
    ),
    Job(
        id="demo-11",
        source="demo",
        title="Staff Software Engineer",
        company="Atlas Civic",
        url="https://example.com/jobs/atlas-staff",
        location="Remote — United States",
        remote=True,
        salary_min=200000,
        salary_max=240000,
        salary_text="$200k–$240k",
        tags=["python", "distributed systems", "postgresql", "leadership"],
        description="Set technical direction for a civic-tech data platform. Mentorship expected.",
        posted_at="2026-08-05",
    ),
    Job(
        id="demo-12",
        source="demo",
        title="QA Automation Engineer",
        company="Brightline Retail",
        url="https://example.com/jobs/brightline-qa",
        location="Atlanta, GA (hybrid)",
        remote=False,
        salary_min=110000,
        salary_max=135000,
        salary_text="$110k–$135k",
        tags=["playwright", "python", "ci", "quality"],
        description="Grow end-to-end coverage and keep releases from becoming folklore.",
        posted_at="2026-08-03",
    ),
]


def demo_jobs(query: str = "", location: str = "", remote_only: bool = False) -> list[Job]:
    q = (query or "").strip().lower()
    loc = (location or "").strip().lower()
    rows = list(DEMO_JOBS)
    if q:
        rows = [
            job
            for job in rows
            if q in job.title.lower()
            or q in job.company.lower()
            or q in " ".join(job.tags).lower()
            or q in (job.description or "").lower()
        ]
    if loc:
        rows = [job for job in rows if loc in (job.location or "").lower()]
    if remote_only:
        rows = [job for job in rows if job.remote]
    return rows
